ALTER TABLE programs
  MODIFY COLUMN term VARCHAR(120) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS program_terms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  term_label VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT IGNORE INTO program_terms (term_label)
SELECT DISTINCT TRIM(term)
FROM programs
WHERE TRIM(term) <> '';
