CREATE TABLE IF NOT EXISTS dtr_drafts (
  student_id INT NOT NULL PRIMARY KEY,
  work_date DATE NULL,
  time_in VARCHAR(5) NULL,
  time_out VARCHAR(5) NULL,
  time_in_locked TINYINT(1) NOT NULL DEFAULT 0,
  time_out_locked TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dtr_drafts_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB;
