<?php
class Student
{
    private static ?bool $genderColumnReady = null;

    public function __construct(private PDO $db) {}

    public function ensureGenderColumn(): void
    {
        if (self::$genderColumnReady === true) {
            return;
        }

        $stmt = $this->db->query("SHOW COLUMNS FROM students LIKE 'gender'");
        if (!$stmt->fetch()) {
            $this->db->exec('ALTER TABLE students ADD COLUMN gender VARCHAR(20) NULL AFTER year_level');
        }

        self::$genderColumnReady = true;
    }

    /**
     * Staged document compliance definitions ("to Comply" ladder).
     *
     * stage 1 = pre-deployment pack (existing pipeline), stage 2 = endorsement + confidentiality,
     * stage 3 = during/post-OJT documents (unlocked once actively deployed).
     *
     * owner:  'student'     = student uploads, coordinator approves/rejects
     *         'coordinator' = coordinator/system provides the file (student only views)
     */
    public const REQUIREMENTS = [
        // ---- Stage 1: 1st to Comply (pre-deployment) ----
        // COR is collected at registration / admin create (students.cor_file); CV is the student profile.
        'philhealth' => ['name' => 'PhilHealth ID / Health Insurance', 'stage' => 1, 'owner' => 'student', 'notes' => 'Upload scan or photo.'],
        'vaccine_card' => ['name' => 'Vaccination Card', 'stage' => 1, 'owner' => 'student', 'notes' => 'Upload scan or photo.'],
        'guardian_consent' => ['name' => 'Parent/Guardian Consent Form', 'stage' => 1, 'owner' => 'student', 'notes' => 'Download the template, then submit the notarized file.'],
        'guardian_id' => ['name' => "Parent/Guardian's Valid ID", 'stage' => 1, 'owner' => 'student', 'notes' => 'Upload scan or photo.'],

        // ---- Stage 2: 2nd to Comply ----
        'endorsement_letter' => ['name' => 'Endorsement Letter', 'stage' => 2, 'owner' => 'coordinator', 'notes' => 'Generated by your coordinator when your documents are forwarded to the Host Training Establishment.'],
        'confidentiality_agreement' => ['name' => 'Confidentiality Agreement', 'stage' => 2, 'owner' => 'student', 'notes' => 'Download the template, then submit the signed file.'],

        // ---- Stage 3: 3rd to Comply (during / after OJT) ----
        'company_profile_doc' => [
            'name' => 'Company Profile',
            'stage' => 3,
            'owner' => 'student',
            'notes' => 'Profile of your Host Training Establishment.',
            'kind' => 'form',
            'form_key' => 'company_profile',
        ],
        'job_description_doc' => [
            'name' => 'Job Description',
            'stage' => 3,
            'owner' => 'student',
            'notes' => 'Job description for your OJT role.',
            'kind' => 'form',
            'form_key' => 'job_description',
        ],
        'personal_observation_doc' => [
            'name' => 'Personal Observation',
            'stage' => 3,
            'owner' => 'student',
            'notes' => 'Your learnings, insights, and observations during OJT.',
            'kind' => 'form',
            'form_key' => 'personal_observation',
        ],

        // Final-requirement evaluations (merged into 3rd to Comply)
        'industry_partner_evaluation' => [
            'name' => 'Host Training Establishment Evaluation',
            'stage' => 3,
            'owner' => 'student',
            'notes' => 'Evaluate your OJT experience by rating your Host Training Establishment and OJT Supervisor.',
            'kind' => 'evaluation',
            'evaluation_key' => 'industry_partner',
        ],
        'coordinator_evaluation' => [
            'name' => 'OJT Coordinator Evaluation',
            'stage' => 3,
            'owner' => 'student',
            'notes' => 'Evaluate the support and guidance provided by your OJT Coordinator.',
            'kind' => 'evaluation',
            'evaluation_key' => 'coordinator',
        ],
    ];

    public const STAGE_LABELS = [
        1 => '1st to Comply',
        2 => '2nd to Comply',
        3 => '3rd to Comply',
    ];

    public function create(int $userId, string $studentNo, string $course, string $yearLevel, string $corFile, int $coordinatorId, ?int $programId = null, string $section = '', ?string $birthdate = null): int
    {
        $stmt = $this->db->prepare('INSERT INTO students (user_id, student_no, program_id, course, year_level, section, birthdate, cor_file, coordinator_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)');
        $stmt->execute([$userId, $studentNo, $programId, $course, $yearLevel, $section, $birthdate, $corFile, $coordinatorId]);
        return (int)$this->db->lastInsertId();
    }

    public function allByCoordinator(int $coordinatorUserId): array
    {
        (new Company($this->db))->ensureMoaMouSupport();
        $stmt = $this->db->prepare('SELECT s.*, u.name, u.email, u.is_active, p.code program_code, p.required_hours program_required_hours, e.id enrollment_id, e.status deployment_status, e.predeployment_status, e.academic_term, e.required_hours, e.orientation_datetime, e.orientation_notes, e.official_start_date, e.projected_end_date, e.end_date, COALESCE(SUM(CASE WHEN d.verification_status = "approved" THEN d.hours ELSE 0 END), 0) rendered_hours, pc.id company_id, pc.name company_name, pc.moa_mou_file company_moa_mou_file FROM students s JOIN users u ON u.id = s.user_id LEFT JOIN programs p ON p.id = s.program_id LEFT JOIN ojt_enrollments e ON e.student_id = s.id LEFT JOIN daily_time_records d ON d.student_id = s.id LEFT JOIN partner_companies pc ON pc.id = e.company_id WHERE s.coordinator_id = ? GROUP BY s.id, u.id, p.id, e.id, pc.id ORDER BY u.name');
        $stmt->execute([$coordinatorUserId]);
        return $stmt->fetchAll();
    }

    public function all(): array
    {
        return $this->db->query('SELECT s.*, u.name, u.email, c.name coordinator_name FROM students s JOIN users u ON u.id = s.user_id LEFT JOIN users c ON c.id = s.coordinator_id ORDER BY u.name')->fetchAll();
    }

    public function allForAdmin(): array
    {
        (new Company($this->db))->ensureMoaMouSupport();
        $rows = $this->db->query(
            'SELECT s.*, u.id AS user_id, u.first_name, u.middle_name, u.last_name, u.name, u.email, u.is_active,
                    p.code program_code, p.required_hours program_required_hours,
                    e.id enrollment_id, e.status deployment_status, e.predeployment_status,
                    e.required_hours, e.orientation_datetime, e.orientation_notes,
                    e.official_start_date, e.projected_end_date,
                    COALESCE(SUM(CASE WHEN d.verification_status = "approved" THEN d.hours ELSE 0 END), 0) rendered_hours,
                    pc.id company_id, pc.name company_name, pc.moa_mou_file company_moa_mou_file,
                    coord.name coordinator_name
             FROM students s
             JOIN users u ON u.id = s.user_id
             LEFT JOIN users coord ON coord.id = s.coordinator_id
             LEFT JOIN programs p ON p.id = s.program_id
             LEFT JOIN ojt_enrollments e ON e.student_id = s.id
             LEFT JOIN daily_time_records d ON d.student_id = s.id
             LEFT JOIN partner_companies pc ON pc.id = e.company_id
             GROUP BY s.id, u.id, p.id, e.id, pc.id, coord.id
             ORDER BY u.last_name ASC, u.first_name ASC, u.id DESC'
        )->fetchAll();

        $studentModel = new Student($this->db);
        foreach ($rows as &$row) {
            $row['predeployment_status'] = $studentModel->effectivePredeploymentStatus(
                (int)$row['id'],
                $row['predeployment_status'] ?? null
            );
        }
        unset($row);

        return $rows;
    }

    public function find(int $id): ?array
    {
        $stmt = $this->db->prepare('SELECT s.*, u.name, u.email, u.is_active, c.name coordinator_name, c.email coordinator_email FROM students s JOIN users u ON u.id = s.user_id LEFT JOIN users c ON c.id = s.coordinator_id WHERE s.id = ?');
        $stmt->execute([$id]);
        return $stmt->fetch() ?: null;
    }

    public function existsByStudentNo(string $studentNo): bool
    {
        $studentNo = trim($studentNo);
        if ($studentNo === '') {
            return false;
        }

        $stmt = $this->db->prepare('SELECT COUNT(*) FROM students WHERE student_no = ?');
        $stmt->execute([$studentNo]);
        return (int)$stmt->fetchColumn() > 0;
    }

    public function belongsToCoordinator(int $studentId, int $coordinatorUserId): bool
    {
        $stmt = $this->db->prepare('SELECT COUNT(*) FROM students WHERE id = ? AND coordinator_id = ?');
        $stmt->execute([$studentId, $coordinatorUserId]);
        return (int)$stmt->fetchColumn() > 0;
    }

    public function findByUser(int $userId): ?array
    {
        $this->ensureGenderColumn();

        $stmt = $this->db->prepare('SELECT s.*, u.first_name, u.middle_name, u.last_name, u.name, u.email, c.name coordinator_name, c.email coordinator_email FROM students s JOIN users u ON u.id = s.user_id LEFT JOIN users c ON c.id = s.coordinator_id WHERE s.user_id = ?');
        $stmt->execute([$userId]);
        return $stmt->fetch() ?: null;
    }

    public function countByCoordinator(int $coordinatorUserId): int
    {
        $stmt = $this->db->prepare('SELECT COUNT(*) FROM students WHERE coordinator_id = ?');
        $stmt->execute([$coordinatorUserId]);
        return (int)$stmt->fetchColumn();
    }

    public function updateProfile(int $studentId, array $data, ?string $photoFile): void
    {
        $this->ensureGenderColumn();

        $stmt = $this->db->prepare('UPDATE students SET address = ?, contact_number = ?, emergency_contact_name = ?, emergency_contact_number = ?, guardian_name = ?, guardian_contact = ?, year_level = ?, gender = ?, photo_file = COALESCE(?, photo_file), profile_completed = 1 WHERE id = ?');
        $stmt->execute([
            trim($data['address'] ?? ''),
            trim($data['contact_number'] ?? ''),
            trim($data['emergency_contact_name'] ?? ''),
            trim($data['emergency_contact_number'] ?? ''),
            trim($data['guardian_name'] ?? ''),
            trim($data['guardian_contact'] ?? ''),
            trim($data['year_level'] ?? ''),
            trim($data['gender'] ?? ''),
            $photoFile,
            $studentId,
        ]);
    }

    /**
     * Stage 1 (pre-deployment) definitions. Kept as the default so the existing
     * pre-deployment pipeline (submit -> review -> forward) stays scoped to stage 1.
     */
    public function requirementDefinitions(): array
    {
        return $this->requirementDefinitionsByStage(1);
    }

    /**
     * Requirement definitions for a specific comply stage, in declaration order.
     */
    public function requirementDefinitionsByStage(int $stage): array
    {
        $defs = [];
        foreach (self::REQUIREMENTS as $key => $def) {
            if ((int)$def['stage'] === $stage) {
                $defs[$key] = [
                    'name' => $def['name'],
                    'notes' => $def['notes'],
                    'owner' => $def['owner'],
                    'stage' => (int)$def['stage'],
                    'kind' => $def['kind'] ?? 'upload',
                    'evaluation_key' => $def['evaluation_key'] ?? null,
                    'form_key' => $def['form_key'] ?? null,
                ];
            }
        }
        return $defs;
    }

    /**
     * Full requirement map across all stages (name/notes/owner/stage), in order.
     */
    public function allRequirementDefinitions(): array
    {
        $defs = [];
        foreach (self::REQUIREMENTS as $key => $def) {
            $defs[$key] = ['name' => $def['name'], 'notes' => $def['notes'], 'owner' => $def['owner'], 'stage' => (int)$def['stage']];
        }
        return $defs;
    }

    public function requirementStage(string $key): int
    {
        return (int)(self::REQUIREMENTS[$key]['stage'] ?? 0);
    }

    public function requirementOwner(string $key): string
    {
        return (string)(self::REQUIREMENTS[$key]['owner'] ?? 'student');
    }

    public function normalizePredeploymentStatus(?string $status): string
    {
        $status = trim((string)$status);
        return in_array($status, ['not_submitted', 'submitted', 'approved', 'needs_revision', 'forwarded', 'accepted', 'orientation_scheduled', 'orientation_completed'], true)
            ? $status
            : 'not_submitted';
    }

    public function effectivePredeploymentStatus(int $studentId, ?string $currentStatus = null, ?array $requirements = null): string
    {
        $currentStatus = $this->normalizePredeploymentStatus($currentStatus);
        if (in_array($currentStatus, ['forwarded', 'accepted', 'orientation_scheduled', 'orientation_completed'], true)) {
            return $currentStatus;
        }

        $requirements ??= $this->requirements($studentId);
        $hasRejected = false;
        $allApproved = true;
        foreach ($requirements as $requirement) {
            $hasFile = !empty($requirement['file_path']);
            $status = trim((string)($requirement['status'] ?? 'pending'));
            if ($hasFile && $status === 'rejected') {
                $hasRejected = true;
            }
            if (!$hasFile || $status !== 'approved') {
                $allApproved = false;
            }
        }
        if ($allApproved) {
            return 'approved';
        }
        if ($hasRejected) {
            return 'needs_revision';
        }
        return $currentStatus;
    }

    /**
     * Keep enrollment.predeployment_status aligned once every stage-1 file is coordinator-approved.
     * Uses the raw DB row (byStudent) — detailsByStudent overlays effective status and would
     * skip the write once files are already approved.
     */
    public function syncPredeploymentStatusIfComplete(int $studentId): bool
    {
        $enrollment = (new Enrollment($this->db))->byStudent($studentId);
        if (!$enrollment) {
            return false;
        }
        $current = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');
        if (!in_array($current, ['submitted', 'not_submitted'], true)) {
            return false;
        }
        if (!$this->hasCompleteRequirements($studentId) || !$this->hasApprovedRequirements($studentId)) {
            return false;
        }
        (new Enrollment($this->db))->setPredeploymentStatus($studentId, 'approved');

        return true;
    }

    /**
     * Realign predeployment_status after stage-1 requirement definitions change
     * (e.g. removed keys). Does not downgrade advanced pipeline states or approved.
     *
     * @return string|null New status, unchanged status, or null when no enrollment
     */
    public function reconcilePredeploymentAfterRequirementDefChange(int $studentId): ?string
    {
        $enrollment = (new Enrollment($this->db))->byStudent($studentId);
        if (!$enrollment) {
            return null;
        }

        $current = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');
        if ($this->isPredeploymentPipelineAdvanced($current)) {
            return $current;
        }
        if (!in_array($current, ['not_submitted', 'needs_revision', 'submitted'], true)) {
            return $current;
        }

        if ($this->hasApprovedRequirements($studentId)) {
            $next = 'approved';
        } elseif ($this->hasRejectedRequirements($studentId)) {
            $next = 'needs_revision';
        } elseif ($this->hasCompleteRequirements($studentId)) {
            $next = 'submitted';
        } else {
            $next = 'not_submitted';
        }

        if ($next !== $current) {
            (new Enrollment($this->db))->setPredeploymentStatus($studentId, $next);
        }

        return $next;
    }

    /**
     * @return array{scanned:int, updated:int, unchanged:int}
     */
    public function reconcileAllPredeploymentAfterRequirementDefChange(): array
    {
        $rows = $this->db->query(
            'SELECT student_id, predeployment_status FROM ojt_enrollments
             WHERE predeployment_status IN ("not_submitted", "needs_revision", "submitted")'
        )->fetchAll();

        $scanned = 0;
        $updated = 0;
        $unchanged = 0;
        foreach ($rows as $row) {
            $scanned++;
            $studentId = (int)$row['student_id'];
            $before = $this->normalizePredeploymentStatus($row['predeployment_status'] ?? 'not_submitted');
            $after = $this->reconcilePredeploymentAfterRequirementDefChange($studentId);
            if ($after !== null && $after !== $before) {
                $updated++;
            } else {
                $unchanged++;
            }
        }

        return ['scanned' => $scanned, 'updated' => $updated, 'unchanged' => $unchanged];
    }

    /**
     * @return array<int, bool>
     */
    public function documentStageAccess(int $studentId): array
    {
        return [
            1 => $this->canAccessStage($studentId, 1),
            2 => $this->canAccessStage($studentId, 2),
            3 => $this->canAccessStage($studentId, 3),
        ];
    }

    public function highestAccessibleDocumentStage(int $studentId): int
    {
        for ($stage = 3; $stage >= 1; $stage--) {
            if ($this->canAccessStage($studentId, $stage)) {
                return $stage;
            }
        }

        return 1;
    }

    /**
     * Stage 1 (pre-deployment) requirements only. The pre-deployment pipeline
     * depends on this returning ONLY stage-1 rows, so stage 2/3 rows in the same
     * table never leak into forward/approval gating.
     */
    public function requirements(int $studentId): array
    {
        return $this->stageRequirements($studentId, 1);
    }

    /**
     * Reconciled requirement rows for one comply stage, keyed by requirement_key,
     * in definition order. Missing rows are synthesized as 'pending'.
     */
    public function stageRequirements(int $studentId, int $stage): array
    {
        $defs = $this->requirementDefinitionsByStage($stage);
        if (!$defs) {
            return [];
        }
        $stmt = $this->db->prepare('SELECT * FROM student_requirements WHERE student_id = ?');
        $stmt->execute([$studentId]);
        $stored = [];
        foreach ($stmt->fetchAll() as $row) {
            $stored[$row['requirement_key']] = $row;
        }
        $rows = [];
        foreach ($defs as $key => $def) {
            if (!isset($stored[$key])) {
                $rows[$key] = ['requirement_key' => $key, 'requirement_name' => $def['name'], 'notes' => $def['notes'], 'file_path' => null, 'status' => 'pending'];
            } else {
                $rows[$key] = $stored[$key];
                $rows[$key]['review_notes'] = $stored[$key]['notes'] ?? '';
                $rows[$key]['notes'] = $def['notes'];
            }
            $rows[$key]['stage'] = (int)$def['stage'];
            $rows[$key]['owner'] = $def['owner'];
            $rows[$key]['kind'] = $def['kind'] ?? 'upload';
            $rows[$key]['evaluation_key'] = $def['evaluation_key'] ?? null;
            $rows[$key]['form_key'] = $def['form_key'] ?? null;
        }
        if ($stage === 3) {
            $evalRow = (new StudentEvaluation($this->db))->getByStudent($studentId);
            foreach ($rows as $key => &$row) {
                if (($row['kind'] ?? 'upload') !== 'evaluation') {
                    continue;
                }
                $evalKey = (string)($row['evaluation_key'] ?? '');
                $submitted = $evalKey !== '' && StudentEvaluation::statusFor($evalRow, $evalKey) === 'submitted';
                $row['status'] = $submitted ? 'approved' : 'pending';
            }
            unset($row);
        }
        return $rows;
    }

    /**
     * Batch version of requirements() to avoid N+1 queries.
     * Returns the full requirement set (with defaults) for every id, keyed by student_id.
     *
     * @param int[] $studentIds
     * @return array<int, array<string, array<string, mixed>>>
     */
    public function requirementsForStudents(array $studentIds): array
    {
        $ids = array_values(array_unique(array_map('intval', $studentIds)));
        $result = [];
        if (!$ids) {
            return $result;
        }
        $placeholders = implode(', ', array_fill(0, count($ids), '?'));
        $stmt = $this->db->prepare("SELECT * FROM student_requirements WHERE student_id IN ($placeholders)");
        $stmt->execute($ids);
        $byStudent = [];
        foreach ($stmt->fetchAll() as $row) {
            $byStudent[(int)$row['student_id']][$row['requirement_key']] = $row;
        }
        $defs = $this->requirementDefinitions();
        foreach ($ids as $sid) {
            $stored = $byStudent[$sid] ?? [];
            $rows = [];
            foreach ($defs as $key => $def) {
                if (!isset($stored[$key])) {
                    $rows[$key] = ['requirement_key' => $key, 'requirement_name' => $def['name'], 'notes' => $def['notes'], 'file_path' => null, 'status' => 'pending'];
                } else {
                    $rows[$key] = $stored[$key];
                    $rows[$key]['review_notes'] = $stored[$key]['notes'] ?? '';
                    $rows[$key]['notes'] = $def['notes'];
                }
            }
            $result[$sid] = $rows;
        }
        return $result;
    }

    /**
     * Count stage 2/3 student-owned upload files awaiting coordinator review.
     *
     * @param int[] $studentIds
     * @return array<int, int>
     */
    public function countPendingFinalReviewsByStudents(array $studentIds): array
    {
        $ids = array_values(array_unique(array_map('intval', $studentIds)));
        $counts = array_fill_keys($ids, 0);
        if (!$ids) {
            return $counts;
        }

        $reviewKeys = [];
        foreach (self::REQUIREMENTS as $key => $def) {
            if ((int)($def['stage'] ?? 0) < 2) {
                continue;
            }
            if (($def['owner'] ?? 'student') !== 'student') {
                continue;
            }
            if (($def['kind'] ?? 'upload') === 'evaluation') {
                continue;
            }
            $reviewKeys[] = $key;
        }
        if (!$reviewKeys) {
            return $counts;
        }

        $idPlaceholders = implode(', ', array_fill(0, count($ids), '?'));
        $keyPlaceholders = implode(', ', array_fill(0, count($reviewKeys), '?'));
        $stmt = $this->db->prepare(
            "SELECT student_id, COUNT(*) AS pending_count
             FROM student_requirements
             WHERE student_id IN ($idPlaceholders)
               AND requirement_key IN ($keyPlaceholders)
               AND status = 'uploaded'
               AND file_path IS NOT NULL
               AND file_path != ''
             GROUP BY student_id"
        );
        $stmt->execute([...$ids, ...$reviewKeys]);
        foreach ($stmt->fetchAll() as $row) {
            $counts[(int)$row['student_id']] = (int)$row['pending_count'];
        }

        return $counts;
    }

    public function saveRequirement(int $studentId, string $key, string $filePath): void
    {
        if (!isset(self::REQUIREMENTS[$key])) {
            throw new RuntimeException('Invalid requirement.');
        }
        $kind = self::REQUIREMENTS[$key]['kind'] ?? 'upload';
        if ($kind === 'evaluation') {
            throw new RuntimeException('Complete this requirement using the evaluation form in 3rd to Comply.');
        }
        if ($kind === 'form' && !requirement_is_form_path($filePath)) {
            throw new RuntimeException('Complete this requirement using the form in 3rd to Comply.');
        }
        if ($kind !== 'form' && requirement_is_form_path($filePath)) {
            throw new RuntimeException('Invalid requirement file path.');
        }
        $name = self::REQUIREMENTS[$key]['name'];
        $existingStmt = $this->db->prepare('SELECT status FROM student_requirements WHERE student_id = ? AND requirement_key = ? LIMIT 1');
        $existingStmt->execute([$studentId, $key]);
        $existing = $existingStmt->fetch() ?: [];
        $stmt = $this->db->prepare('INSERT INTO student_requirements (student_id, requirement_key, requirement_name, file_path, status, uploaded_at) VALUES (?, ?, ?, ?, "uploaded", NOW()) ON DUPLICATE KEY UPDATE file_path = VALUES(file_path), status = "uploaded", uploaded_at = NOW()');
        $stmt->execute([$studentId, $key, $name, $filePath]);

        // Pre-deployment (stage 1) auto-status side-effect only.
        if ($this->requirementStage($key) === 1) {
            $enrollment = (new Enrollment($this->db))->detailsByStudent($studentId);
            if (($existing['status'] ?? '') === 'rejected' || ($enrollment['predeployment_status'] ?? '') === 'needs_revision') {
                $nextStatus = $this->hasRejectedRequirements($studentId)
                    ? 'needs_revision'
                    : ($this->hasCompleteRequirements($studentId) ? 'submitted' : 'not_submitted');
                (new Enrollment($this->db))->setPredeploymentStatus($studentId, $nextStatus);
            }
        }
    }

    /**
     * Mark a structured form requirement as submitted (sentinel file_path).
     */
    public function saveFormRequirement(int $studentId, string $key): void
    {
        if ((self::REQUIREMENTS[$key]['kind'] ?? 'upload') !== 'form') {
            throw new RuntimeException('Invalid form requirement.');
        }
        $this->saveRequirement($studentId, $key, requirement_form_path($key));
    }

    public function reviewRequirement(int $studentId, string $key, string $status, string $notes = ''): void
    {
        if (!in_array($status, ['approved', 'rejected'], true)) {
            throw new RuntimeException('Invalid review status.');
        }
        if (!isset(self::REQUIREMENTS[$key])) {
            throw new RuntimeException('Invalid requirement.');
        }
        $stage = $this->requirementStage($key);
        if (($this->requirementOwner($key) ?? 'student') !== 'student') {
            throw new RuntimeException('Only student-uploaded documents can be reviewed here.');
        }
        // Stage 1 keeps its "student must submit for review first" gate, except late uploads
        // while the student is already in the deployment pipeline (e.g. late-added requirement).
        if ($stage === 1 && !$this->canCoordinatorReviewStage1Requirement($studentId, $key)) {
            throw new RuntimeException('This requirement is not ready for coordinator review.');
        }
        if ($stage !== 1 && !$this->canCoordinatorReviewUploadedRequirement($studentId, $key)) {
            throw new RuntimeException('This requirement is not ready for coordinator review.');
        }
        $stmt = $this->db->prepare('UPDATE student_requirements SET status = ?, notes = ?, reviewed_at = NOW() WHERE student_id = ? AND requirement_key = ? AND file_path IS NOT NULL');
        $stmt->execute([$status, $notes, $studentId, $key]);
        if ($stmt->rowCount() === 0) {
            throw new RuntimeException('Requirement file is not available for review.');
        }
    }

    /**
     * Whether a comply stage is currently accessible for the student.
     * stage 1: enrolled. stage 2: pre-deployment approved (or later). stage 3: actively deployed.
     */
    public function canAccessStage(int $studentId, int $stage): bool
    {
        $enrollment = (new Enrollment($this->db))->detailsByStudent($studentId);
        if (!$enrollment) {
            return false;
        }
        if ($stage === 1) {
            return true;
        }
        $predeployment = $this->effectivePredeploymentStatus($studentId, $enrollment['predeployment_status'] ?? null);
        if ($stage === 2) {
            return in_array($predeployment, ['approved', 'forwarded', 'accepted', 'orientation_scheduled', 'orientation_completed'], true);
        }
        if ($stage === 3) {
            $deploymentStatus = (string)($enrollment['status'] ?? 'pending');
            return in_array($deploymentStatus, ['active', 'completed'], true);
        }
        return false;
    }

    /**
     * Aggregate status for a comply stage:
     * 'locked' | 'not_started' | 'in_progress' | 'submitted' | 'needs_revision' | 'approved'.
     */
    public function stageAggregateStatus(int $studentId, int $stage): string
    {
        if (!$this->canAccessStage($studentId, $stage)) {
            return 'locked';
        }

        if ($stage === 1) {
            $enrollment = (new Enrollment($this->db))->detailsByStudent($studentId);
            if ($enrollment) {
                $predeployment = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');
                if ($predeployment === 'needs_revision') {
                    return 'needs_revision';
                }
                if (in_array($predeployment, ['approved', 'forwarded', 'accepted', 'orientation_scheduled', 'orientation_completed'], true)) {
                    return 'approved';
                }
                if ($predeployment === 'submitted') {
                    return 'submitted';
                }
            }
        }

        $rows = $this->stageRequirements($studentId, $stage);
        // Only student-owned items drive the aggregate compliance state.
        $studentRows = array_filter($rows, static fn ($r) => ($r['owner'] ?? 'student') === 'student');
        if (!$studentRows) {
            return 'approved';
        }
        $total = count($studentRows);
        $approved = 0;
        $hasRejected = false;
        $withFile = 0;
        $anyFile = false;
        foreach ($studentRows as $r) {
            $kind = $r['kind'] ?? 'upload';
            $hasFile = !empty($r['file_path']);
            $st = (string)($r['status'] ?? 'pending');
            if ($kind === 'evaluation') {
                if ($st === 'approved') {
                    $approved++;
                    $withFile++;
                    $anyFile = true;
                }
                continue;
            }
            if ($hasFile) {
                $withFile++;
                $anyFile = true;
            }
            if ($hasFile && $st === 'approved') {
                $approved++;
            }
            if ($hasFile && $st === 'rejected') {
                $hasRejected = true;
            }
        }
        if ($approved === $total) {
            return 'approved';
        }
        if ($hasRejected) {
            return 'needs_revision';
        }
        if ($stage === 1) {
            // Stage 1 must be formally submitted before it reads as under review.
            if ($withFile === $total) {
                return 'in_progress';
            }
        } elseif ($withFile === $total) {
            return 'submitted';
        }
        if ($withFile > 0) {
            return 'in_progress';
        }
        if ($anyFile) {
            return 'in_progress';
        }
        return 'not_started';
    }

    public function hasCompleteRequirements(int $studentId): bool
    {
        foreach ($this->requirements($studentId) as $req) {
            if (empty($req['file_path'])) {
                return false;
            }
        }
        return true;
    }

    public function hasRejectedRequirements(int $studentId): bool
    {
        foreach ($this->requirements($studentId) as $req) {
            if (!empty($req['file_path']) && ($req['status'] ?? '') === 'rejected') {
                return true;
            }
        }
        return false;
    }

    /**
     * Single reconciled requirement row for a key (any stage), or null.
     */
    public function requirementRow(int $studentId, string $key): ?array
    {
        $stage = $this->requirementStage($key);
        if ($stage === 0) {
            return null;
        }
        $rows = $this->stageRequirements($studentId, $stage);
        return $rows[$key] ?? null;
    }

    public function canUploadRequirement(int $studentId, string $key): bool
    {
        $requirement = $this->requirementRow($studentId, $key);
        if ($requirement === null) {
            return false;
        }
        if (($requirement['kind'] ?? 'upload') === 'evaluation') {
            return false;
        }
        // Form requirements are saved via structured forms, not file upload — but the same
        // empty/rejected gate controls whether the student may submit/edit the form.
        if (($requirement['owner'] ?? 'student') !== 'student') {
            return false;
        }
        $enrollment = (new Enrollment($this->db))->detailsByStudent($studentId);
        if (!$enrollment) {
            return false;
        }
        $stage = $this->requirementStage($key);
        if (!$this->canAccessStage($studentId, $stage)) {
            return false;
        }
        $status = $requirement['status'] ?? 'pending';
        $hasFile = !empty($requirement['file_path']);

        if ($stage === 1) {
            if ($status === 'rejected') {
                return true;
            }
            if ($hasFile) {
                return false;
            }
            // Missing files stay uploadable (e.g. late-added requirement after other docs were approved).
            return true;
        }

        // Stage 2/3: allow (re)upload when empty or rejected; lock once uploaded/approved.
        if ($status === 'rejected') {
            return true;
        }
        return !$hasFile;
    }

    public function requirementUploadMessage(int $studentId, string $key): string
    {
        $requirement = $this->requirementRow($studentId, $key);
        if ($requirement === null) {
            return 'Unavailable';
        }
        $stage = $this->requirementStage($key);
        if (($requirement['kind'] ?? 'upload') === 'evaluation') {
            if (!$this->canAccessStage($studentId, $stage)) {
                return 'Locked';
            }
            $evalKey = (string)($requirement['evaluation_key'] ?? '');
            $evalRow = (new StudentEvaluation($this->db))->getByStudent($studentId);
            if ($evalKey !== '' && StudentEvaluation::statusFor($evalRow, $evalKey) === 'submitted') {
                return 'Completed';
            }
            return 'Complete the evaluation form';
        }
        if (($requirement['kind'] ?? 'upload') === 'form') {
            if (!$this->canAccessStage($studentId, $stage)) {
                return 'Locked';
            }
            $status = $requirement['status'] ?? 'pending';
            $hasFile = !empty($requirement['file_path']);
            if ($status === 'approved') {
                return 'Approved';
            }
            if ($status === 'rejected') {
                return 'Update the rejected form';
            }
            if ($hasFile) {
                return 'Awaiting review';
            }
            return 'Fill out the form';
        }
        $owner = $requirement['owner'] ?? 'student';
        $status = $requirement['status'] ?? 'pending';
        $hasFile = !empty($requirement['file_path']);
        $enrollment = (new Enrollment($this->db))->detailsByStudent($studentId);
        if (!$enrollment) return 'Enrollment required';

        if ($owner === 'coordinator') {
            return $hasFile ? 'Provided by coordinator' : 'Waiting for coordinator';
        }
        if (!$this->canAccessStage($studentId, $stage)) {
            return 'Locked';
        }
        if ($status === 'approved') return 'Approved';
        if ($status === 'uploaded' && $hasFile) return 'Awaiting review';
        if ($status === 'rejected') return 'Replace the rejected file';

        if ($stage === 1) {
            $predeploymentStatus = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');
            if ($status === 'approved') {
                return 'Approved';
            }
            if ($status === 'rejected') {
                return 'Replace the rejected file';
            }
            if (!$hasFile) {
                return 'Ready to upload';
            }
            if ($predeploymentStatus === 'submitted') {
                return 'Under review';
            }
            if (in_array($predeploymentStatus, ['approved', 'forwarded', 'accepted', 'orientation_scheduled', 'orientation_completed'], true)) {
                return 'Uploaded';
            }
        }
        if ($hasFile) return 'Already uploaded';
        return 'Ready to upload';
    }

    public function hasApprovedRequirements(int $studentId): bool
    {
        foreach ($this->requirements($studentId) as $req) {
            if (empty($req['file_path']) || ($req['status'] ?? '') !== 'approved') {
                return false;
            }
        }
        return true;
    }

    /** Deployment pipeline states where global predeployment status must be preserved. */
    public function isPredeploymentPipelineAdvanced(?string $status): bool
    {
        return in_array(
            $this->normalizePredeploymentStatus($status),
            ['forwarded', 'accepted', 'orientation_scheduled', 'orientation_completed'],
            true
        );
    }

    /** Stage-1 files uploaded by the student and waiting for coordinator action. */
    public function hasPendingStage1Reviews(int $studentId): bool
    {
        foreach ($this->requirements($studentId) as $req) {
            if (!empty($req['file_path']) && ($req['status'] ?? '') === 'uploaded') {
                return true;
            }
        }

        return false;
    }

    public function canCoordinatorReviewUploadedRequirement(int $studentId, string $key): bool
    {
        if ($this->requirementOwner($key) !== 'student') {
            return false;
        }
        if ((self::REQUIREMENTS[$key]['kind'] ?? 'upload') === 'evaluation') {
            return false;
        }
        $requirement = $this->requirementRow($studentId, $key);
        if ($requirement === null || empty($requirement['file_path'])) {
            return false;
        }
        $status = (string)($requirement['status'] ?? '');

        return in_array($status, ['uploaded', 'approved'], true);
    }

    public function canCoordinatorReviewStage1Requirement(int $studentId, string $key): bool
    {
        $requirement = $this->requirementRow($studentId, $key);
        if ($requirement === null || empty($requirement['file_path'])) {
            return false;
        }
        $status = (string)($requirement['status'] ?? '');
        if ($status === 'approved') {
            $enrollment = (new Enrollment($this->db))->byStudent($studentId);
            if (!$enrollment) {
                return false;
            }
            $predeploymentStatus = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');

            return !$this->isPredeploymentPipelineAdvanced($predeploymentStatus);
        }
        if ($status !== 'uploaded') {
            return false;
        }
        $enrollment = (new Enrollment($this->db))->byStudent($studentId);
        if (!$enrollment) {
            return false;
        }
        $predeploymentStatus = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');
        if (in_array($predeploymentStatus, ['submitted', 'needs_revision', 'approved'], true)) {
            return true;
        }

        return $this->isPredeploymentPipelineAdvanced($predeploymentStatus);
    }

    /**
     * Next predeployment_status after a stage-1 review (does not downgrade advanced pipeline states).
     * Reads raw DB status so callers can detect submitted → approved transitions.
     */
    public function predeploymentStatusAfterStage1Review(int $studentId, string $reviewStatus): string
    {
        $enrollment = (new Enrollment($this->db))->byStudent($studentId);
        $current = $this->normalizePredeploymentStatus($enrollment['predeployment_status'] ?? 'not_submitted');
        if ($this->isPredeploymentPipelineAdvanced($current)) {
            return $current;
        }
        if ($reviewStatus === 'rejected') {
            return 'needs_revision';
        }
        if ($this->hasApprovedRequirements($studentId)) {
            return 'approved';
        }

        return $this->hasRejectedRequirements($studentId) ? 'needs_revision' : 'submitted';
    }

    public function requirementFilePaths(int $studentId): array
    {
        return array_values(array_filter(array_map(
            static function ($req) {
                $path = $req['file_path'] ?? null;
                if ($path === null || $path === '' || requirement_is_form_path((string)$path)) {
                    return null;
                }
                return $path;
            },
            $this->requirements($studentId)
        )));
    }
}
